### ISSUE TITLE
Error 404 when trying to import package with TC v10

### ISSUE THREAD

**Issue by T0T4R4** [Inedo/inedox-teamcity#31]
Ref: TeamCityArtifactImporter.cs

The way this extension queries the TC API is obsolete. TC has moved to a different way as explained on [their documentation page](https://confluence.jetbrains.com/display/TCD10/REST+API).

Currently this extension retrieves artifact using the _repository_ path as follows :
`https://teamcity-server/repository/download/{buildType}/{buildId}/{artifactName}`
But **fails** with non-numeric values for {buildId} ( such as 'lastSuccessful' for example )

Instead, the code should :

1. Get the buildTypeId (int) from the 'buildConfigurationId (string)'
https://teamcity-server/httpAuth/app/rest/buildTypes/{buildConfigurationId }

2. [ Fixed by @BenLubar in #41 ] Get the latest buildId (int) for a given branchName (string) and using above buildTypeId (int)
https://teamcity-server/httpAuth/app/rest/builds/?locator=status:success,state:finished,buildType:{buildTypeId},branch:master

3. Get the artifact(s) for the above buildId (int)
`https://teamcity-server/httpAuth/app/rest/builds/id:{buildId}/artifacts/children/`

See an example on my fork :

- method ImportAsync() in [ImportArtifactOperationManager.cs](https://github.com/T0T4R4/bmx-teamcity/blob/develop/Operations/ImportArtifact/ImportArtifactOperationManager.cs)
- [TeamCityAPI.cs](https://github.com/T0T4R4/bmx-teamcity/blob/develop/TeamCityAPI/TeamCityAPI.cs)

Thanks

**Comment by T0T4R4** [comment]
Also I maintain the above points, the import should succeed in the current codebase as #41 fixes a major issue.

**Comment by jrasch** [comment]
We no longer support this version of TeamCity.
