### ISSUE TITLE
Teamcity Url is not working

### ISSUE THREAD

**Issue by semacdi** [Inedo/inedox-teamcity#44]
Teamcity 2017.2.2 has :id in the artifact download url.

In TeamCityAtrifactImporter the url should look like:
string relativeUrl = string.Format("repository/download/{0}/{1}:id/{2}", this.BuildConfigurationId, this.BuildNumber, this.ArtifactName);

**Comment by semacdi** [comment]
It also looks like they have removed httpAuth.

http://myserver/repository/download/myConfigId/5308:id/myartifact.zip

**Comment by jrasch** [comment]
Unfortunately the previous change to resolve this had to be reverted.

Going forward, if you would like to specify a build ID instead of a name, just append `:id` in the `BuildNumber` property, e.g.:

```
Import-Artifact
(
    Project: MyProject,
    BuildConfigurationId: Release,
    BuildNumber: 1234:id
);
```
