### ISSUE TITLE
Unable to build the source control because of pre Inedo.SDK package

### ISSUE THREAD

**Issue by semacdi** [Inedo/inedox-teamcity#45]
The code is referencing the pre release of Inedo.SDK which is not available on nuget.  SDK.CreateArtifactAsync does not exist.  What is the legacy call I can reference instead so I can get it to build?

**Comment by jrasch** [comment]
That call should have the equivalent arguments to `Artifact.CreateAsync()` in the Inedo.BuildMaster.SDK

You can also download a pre-release version to build against here: http://44.inedo.com/inedo/nuget/Inedo.SDK.1.0.4-pre0021.nupkg.zip

**Comment by semacdi** [comment]
Thank you
