### ISSUE TITLE
Some logging return {0} instead of variable value

### ISSUE THREAD

**Issue by T0T4R4** [Inedo/inedox-teamcity#59]
Many places in the code is missing either String.format() or should use string interpolation ${} to include the variables as currently it does not work as you can see below, the LogDebug function does *not* do string replacement properly by itself :

`                this.Logger.LogDebug("Triggering build configuration {0}...", this.BuildConfigurationId);
`
See the output in BM missing the variable value :   

![image](https://user-images.githubusercontent.com/1294511/85084277-acb8b700-b217-11ea-8910-bc5d538ef5ac.png)

**Comment by rhessinger** [comment]
Hi @T0T4R4 ,

I have added a new prerelease of this extension including the fix, version [1.7.2-RC.4](https://proget.inedo.com/feeds/PrereleaseExtensions/inedox/TeamCity/1.7.2-RC.4).  I need to check on the status of the other change that is supposed to go out in the final release of this extension, but you can install the pre-release extension by following the instructions [here](https://docs.inedo.com/docs/buildmaster/reference/extensions#manual-install).

Thanks,
Rich

**Comment by T0T4R4** [comment]
Thanks mate.
