### ISSUE TITLE
Default use of Import-Artifact fails

### ISSUE THREAD

**Issue by jonof** [Inedo/inedox-teamcity#65]
A trivial use of `TeamCity::Import-Artifact()` with no parameters is failing with a "_BuildConfiguration "buildconfigid" not found on Project "projectid"_" error using version 2.2.3-CI.5 of this extension and TeamCity 2023.05.

Judging from code of the [Import-Artifact operation](https://github.com/Inedo/inedox-teamcity/blob/ac913b14cd835733f07d7803401cb0cbfeb14e32/TeamCity/InedoExtension/Operations/ImportTeamCityArtifactOperation.cs#L122-L140), the code of [TeamCityClient's GetProjectBuildTypesAsync method](https://github.com/Inedo/inedox-teamcity/blob/ac913b14cd835733f07d7803401cb0cbfeb14e32/TeamCity/InedoExtension/TeamCityClient.cs#L109-L120) is likely expecting to receive a response from the TeamCity API looking like the one below when it calls https://teamcity/app/rest/projects/projectid?fields=buildTypes:
```
<project>
  <buildTypes>
    <buildType id="buildconfigid" name="Build config name" description="Build config description"
      projectName="Project name" projectId="projectid" href="/app/rest/buildTypes/id:buildconfigid"
      webUrl="http://teamcity/viewType.html?buildTypeId=buildconfigid"/>
  </buildTypes>
</project>
```

Instead, it receives this:
```
<project>
  <buildTypes count="1"/>
</project>
```

I can't confirm exactly how TeamCity behaved in earlier versions, though the text of the 'fields' parmeter in [the TeamCity API documentation](https://www.jetbrains.com/help/teamcity/rest/2020.2/teamcity-rest-api-documentation.html#Full+and+Partial+Responses) states "At this time, the response can sometimes include the fields/elements not specifically requested. This can change in the future versions, so it is recommended to specify all the fields/elements used by the client", but my suspicion is the URL that BuildMaster should be calling ought to be https://teamcity/app/rest/projects/projectid?fields=buildTypes(buildType)

This change should be compatible with TeamCity releases from at least 2020.2.

**Comment by whatatripp** [comment]
Hello, thanks so much for the details :)

It seems this was a regression from 2.2.2, probably due to recent changes. We typically do a very basic test: New Application > Team City > Import Build, but that was definitely broken. But now it works, at least in theory via CI.6 :)
